"""empty message

Revision ID: 601bbccfb8fc
Revises: 6834ba07ea67
Create Date: 2024-05-17 23:16:31.003720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '601bbccfb8fc'
down_revision = '6834ba07ea67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_name_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('user_name_key', ['name'])

    # ### end Alembic commands ###
